#!/usr/bin/env bash
set -euo pipefail

username="${SSH_USERNAME:-root}"
password="${SSH_PASSWORD:-}"

if [[ "$username" != "root" ]] && ! id "$username" >/dev/null 2>&1; then
  useradd -m -s /bin/bash "$username"
fi

if [[ -n "$password" ]]; then
  echo "${username}:${password}" | chpasswd
fi

env_file="/etc/profile.d/gongji-runtime-env.sh"
ssh_env_file="/tmp/gongji-ssh-environment"
{
  for key in CUDA_VISIBLE_DEVICES NVIDIA_VISIBLE_DEVICES PATH LD_LIBRARY_PATH; do
    value="${!key:-}"
    if [[ -n "$value" ]]; then
      printf '%s=%s\n' "$key" "$value"
    fi
  done
} | awk -F= '!seen[$1]++' > "$ssh_env_file"

{
  echo "# Generated by GongJi runtime"
  while IFS='=' read -r key value; do
    printf 'export %s=%q\n' "$key" "$value"
  done < "$ssh_env_file"
} > "$env_file"

if [[ "$username" != "root" ]]; then
  mkdir -p "/home/$username/.ssh"
  cp "$ssh_env_file" "/home/$username/.ssh/environment"
  chown -R "$username:$username" "/home/$username/.ssh"
fi
mkdir -p /root/.ssh
cp "$ssh_env_file" /root/.ssh/environment

while IFS='=' read -r key value; do
  if [[ -n "$key" ]]; then
    printf 'SetEnv %s=%s\n' "$key" "$value" >> /etc/ssh/sshd_config
  fi
done < "$ssh_env_file"

exec /usr/sbin/sshd -D -e
