#!/usr/bin/env bash
set -euo pipefail

username="${SSH_USERNAME:-root}"
password="${SSH_PASSWORD:-}"

if [[ "$username" != "root" ]] && ! id "$username" >/dev/null 2>&1; then
  useradd -m -s /bin/bash "$username"
fi

if [[ -n "$password" ]]; then
  echo "${username}:${password}" | chpasswd
fi

env_file="/etc/profile.d/gongji-runtime-env.sh"
ssh_env_file="/tmp/gongji-ssh-environment"
{
  echo "# Generated by GongJi runtime"
  for key in ASCEND_VISIBLE_DEVICES ASCEND_RT_VISIBLE_DEVICES NPU_VISIBLE_DEVICES; do
    value="${!key:-}"
    if [[ -n "$value" ]]; then
      printf 'export %s=%q\n' "$key" "$value"
    fi
  done
  env | grep -E '^(ASCEND|NPU_VISIBLE|PYTHONPATH|LD_LIBRARY_PATH|PATH|SOC_VERSION|TASK_QUEUE_ENABLE|OMP_NUM_THREADS)=' \
    | while IFS='=' read -r key value; do
        printf 'export %s=%q\n' "$key" "$value"
      done
} > "$env_file"
chmod 0644 "$env_file"

{
  for key in ASCEND_VISIBLE_DEVICES ASCEND_RT_VISIBLE_DEVICES NPU_VISIBLE_DEVICES; do
    value="${!key:-}"
    if [[ -n "$value" ]]; then
      printf '%s=%s\n' "$key" "$value"
    fi
  done
  env | grep -E '^(ASCEND|NPU_VISIBLE|PYTHONPATH|LD_LIBRARY_PATH|PATH|SOC_VERSION|TASK_QUEUE_ENABLE|OMP_NUM_THREADS)='
} | awk -F= '!seen[$1]++' > "$ssh_env_file"

if ! grep -q '^LD_LIBRARY_PATH=.*Ascend/driver/lib64' "$ssh_env_file"; then
  current_ld="${LD_LIBRARY_PATH:-}"
  printf 'LD_LIBRARY_PATH=%s:%s\n' "/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver" "$current_ld" >> "$ssh_env_file"
fi
if ! grep -q '^LD_LIBRARY_PATH=.*aarch64-linux/devlib' "$ssh_env_file"; then
  current_ld="$(grep '^LD_LIBRARY_PATH=' "$ssh_env_file" | tail -n 1 | cut -d= -f2-)"
  grep -v '^LD_LIBRARY_PATH=' "$ssh_env_file" > "${ssh_env_file}.tmp"
  printf 'LD_LIBRARY_PATH=%s:%s\n' "$current_ld" "/usr/local/Ascend/cann-8.5.0/aarch64-linux/devlib:/usr/local/Ascend/cann-8.5.0/aarch64-linux/devlib/device:/usr/local/Ascend/cann-8.5.0/aarch64-linux/devlib/linux/aarch64" >> "${ssh_env_file}.tmp"
  mv "${ssh_env_file}.tmp" "$ssh_env_file"
fi

{
  echo "# Generated by GongJi runtime"
  while IFS='=' read -r key value; do
    printf 'export %s=%q\n' "$key" "$value"
  done < "$ssh_env_file"
} > "$env_file"

if [[ "$username" != "root" ]]; then
  mkdir -p "/home/$username/.ssh"
  cp "$ssh_env_file" "/home/$username/.ssh/environment"
  chown -R "$username:$username" "/home/$username/.ssh"
fi
mkdir -p /root/.ssh
cp "$ssh_env_file" /root/.ssh/environment

while IFS='=' read -r key value; do
  if [[ -n "$key" ]]; then
    printf 'SetEnv %s=%s\n' "$key" "$value" >> /etc/ssh/sshd_config
  fi
done < "$ssh_env_file"

exec /usr/sbin/sshd -D -e
