from __future__ import annotations

import re
import sqlite3
from contextlib import contextmanager
from pathlib import Path
from typing import Any

from psycopg import connect
from psycopg.rows import dict_row

from .config import resolve_database_url, resolve_db_path
from .seed import (
    CARD_PRODUCTS,
    DEFAULT_HISTORY_RENTALS,
    DEFAULT_USERS,
    USER_PRICE_CONFIGS,
    build_cabinets,
    get_allowed_device_indices,
)
from .utils import cabinet_status_from_active_cards


_db_path: Path = resolve_db_path()
_database_url: str | None = resolve_database_url()


def dict_factory(cursor: sqlite3.Cursor, row: tuple) -> dict:
    return {col[0]: row[idx] for idx, col in enumerate(cursor.description)}


class CursorAdapter:
    def __init__(self, cursor: Any):
        self._cursor = cursor

    @property
    def lastrowid(self) -> int | None:
        return getattr(self._cursor, "lastrowid", None)

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    def __getattr__(self, name: str) -> Any:
        return getattr(self._cursor, name)


class ConnectionAdapter:
    def __init__(self, conn: Any, backend: str):
        self._conn = conn
        self.backend = backend

    def execute(self, sql: str, params: Any = None) -> CursorAdapter:
        query, adapted_params = _adapt_query(sql, params, self.backend)
        if adapted_params is None:
            cursor = self._conn.execute(query)
        else:
            cursor = self._conn.execute(query, adapted_params)
        return CursorAdapter(cursor)

    def executemany(self, sql: str, seq_of_params: list[Any]) -> CursorAdapter:
        sample = seq_of_params[0] if seq_of_params else None
        query, _ = _adapt_query(sql, sample, self.backend)
        adapted = [_adapt_params(item, self.backend) for item in seq_of_params]
        if self.backend == "postgres":
            with self._conn.cursor(row_factory=dict_row) as cursor:
                cursor.executemany(query, adapted)
                return CursorAdapter(cursor)
        cursor = self._conn.executemany(query, adapted)
        return CursorAdapter(cursor)

    def execute_insert(self, sql: str, params: Any) -> int:
        if self.backend == "postgres":
            cursor = self.execute(_with_returning_id(sql), params)
            row = cursor.fetchone()
            if not row:
                raise RuntimeError("Insert did not return an id")
            return int(row["id"])
        cursor = self.execute(sql, params)
        if cursor.lastrowid is None:
            raise RuntimeError("Insert did not produce a lastrowid")
        return int(cursor.lastrowid)

    def commit(self) -> None:
        self._conn.commit()

    def rollback(self) -> None:
        self._conn.rollback()

    def close(self) -> None:
        self._conn.close()


def configure_database(db_path: str | Path | None = None, database_url: str | None = None) -> None:
    global _db_path, _database_url
    _db_path = Path(db_path) if db_path else resolve_db_path()
    _database_url = database_url if database_url is not None else resolve_database_url()


def get_database_path() -> Path:
    return _db_path


def get_database_url() -> str | None:
    return _database_url


def get_connection() -> ConnectionAdapter:
    if _database_url:
        conn = connect(_database_url, row_factory=dict_row)
        return ConnectionAdapter(conn, "postgres")

    conn = sqlite3.connect(get_database_path(), detect_types=sqlite3.PARSE_DECLTYPES)
    conn.row_factory = dict_factory
    conn.execute("PRAGMA foreign_keys = ON")
    return ConnectionAdapter(conn, "sqlite")


@contextmanager
def connection_scope() -> ConnectionAdapter:
    conn = get_connection()
    try:
        yield conn
    finally:
        conn.close()


@contextmanager
def transaction() -> ConnectionAdapter:
    conn = get_connection()
    try:
        if conn.backend == "sqlite":
            conn.execute("BEGIN IMMEDIATE")
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def init_db() -> None:
    with connection_scope() as conn:
        for statement in _schema_statements(conn.backend):
            conn.execute(statement)
        _migrate_schema(conn)
        _seed_if_empty(conn)
        _sync_seed_reference_data(conn)
        _sync_gpu_devices_from_cabinets(conn)
        conn.commit()


def _schema_statements(backend: str) -> list[str]:
    identity = "INTEGER PRIMARY KEY AUTOINCREMENT" if backend == "sqlite" else "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return [
        f"""
        CREATE TABLE IF NOT EXISTS card_products (
            id {identity},
            card_type TEXT NOT NULL UNIQUE,
            title TEXT NOT NULL,
            cabinet_desc TEXT NOT NULL,
            vram TEXT NOT NULL,
            cpu TEXT NOT NULL,
            memory TEXT NOT NULL,
            display_price TEXT NOT NULL
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS user_price_configs (
            id {identity},
            card_type TEXT NOT NULL,
            cabinet_type TEXT NOT NULL,
            hourly_user_price REAL NOT NULL,
            enabled INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(card_type, cabinet_type)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS cabinets (
            id {identity},
            cabinet_code TEXT NOT NULL UNIQUE,
            location TEXT NOT NULL,
            card_type TEXT NOT NULL,
            cabinet_type TEXT NOT NULL,
            capacity_cards INTEGER NOT NULL,
            day_hourly_power_cost REAL NOT NULL,
            night_hourly_power_cost REAL NOT NULL,
            status TEXT NOT NULL CHECK(status IN ('available', 'rented', 'offline')),
            last_idle_at TEXT,
            active_card_count INTEGER NOT NULL DEFAULT 0,
            host_ip TEXT,
            ssh_port INTEGER NOT NULL DEFAULT 22
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS gpu_devices (
            id {identity},
            cabinet_id INTEGER NOT NULL,
            gpu_index INTEGER NOT NULL,
            gpu_name TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'available' CHECK(status IN ('available', 'rented', 'disabled')),
            rental_id INTEGER,
            observed_status TEXT NOT NULL DEFAULT 'unknown',
            health TEXT,
            usage_percent REAL,
            memory_used_mb INTEGER,
            memory_total_mb INTEGER,
            process_count INTEGER NOT NULL DEFAULT 0,
            last_seen_at TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(cabinet_id, gpu_index),
            FOREIGN KEY(cabinet_id) REFERENCES cabinets(id) ON DELETE CASCADE
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS users (
            id {identity},
            username TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            phone TEXT,
            nickname TEXT NOT NULL,
            avatar_url TEXT,
            balance REAL NOT NULL DEFAULT 0,
            role TEXT NOT NULL DEFAULT 'user' CHECK(role IN ('user', 'admin')),
            status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'disabled')),
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS user_balance_transactions (
            id {identity},
            user_id INTEGER NOT NULL,
            type TEXT NOT NULL,
            amount REAL NOT NULL,
            balance_after REAL NOT NULL,
            reference_type TEXT,
            reference_id INTEGER,
            remark TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS user_sessions (
            id {identity},
            user_id INTEGER NOT NULL,
            token TEXT NOT NULL UNIQUE,
            status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'revoked')),
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_used_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS rentals (
            id {identity},
            user_id INTEGER,
            card_type TEXT NOT NULL,
            cabinet_type TEXT NOT NULL,
            cabinet_count INTEGER NOT NULL,
            card_count INTEGER,
            started_at TEXT NOT NULL,
            ended_at TEXT,
            duration_seconds INTEGER,
            hourly_user_price_total REAL NOT NULL,
            hourly_power_cost_total REAL NOT NULL,
            user_total_amount REAL,
            power_cost_total REAL,
            status TEXT NOT NULL CHECK(status IN ('active', 'cancelled')),
            stop_reason TEXT,
            ip TEXT NOT NULL,
            password TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS rental_allocations (
            id {identity},
            rental_id INTEGER NOT NULL,
            cabinet_id INTEGER NOT NULL,
            allocated_cards INTEGER NOT NULL DEFAULT 1,
            device_indices TEXT,
            instance_id TEXT,
            container_name TEXT,
            ssh_host TEXT,
            ssh_port INTEGER,
            ssh_username TEXT,
            ssh_password TEXT,
            ssh_command TEXT,
            provisioning_status TEXT,
            hourly_user_price REAL NOT NULL,
            hourly_power_cost REAL NOT NULL,
            FOREIGN KEY(rental_id) REFERENCES rentals(id) ON DELETE CASCADE,
            FOREIGN KEY(cabinet_id) REFERENCES cabinets(id) ON DELETE CASCADE
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS node_heartbeats (
            id {identity},
            node_id TEXT NOT NULL UNIQUE,
            host_ip TEXT NOT NULL,
            accelerator_type TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'online',
            reported_at TEXT,
            last_seen_at TEXT NOT NULL,
            raw TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS node_device_reports (
            id {identity},
            node_id TEXT NOT NULL,
            device_index INTEGER NOT NULL,
            name TEXT,
            health TEXT,
            usage_percent REAL,
            memory_used_mb INTEGER,
            memory_total_mb INTEGER,
            hbm_used_mb INTEGER,
            hbm_total_mb INTEGER,
            process_count INTEGER NOT NULL DEFAULT 0,
            observed_status TEXT NOT NULL DEFAULT 'unknown',
            raw TEXT,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(node_id, device_index)
        )
        """,
    ]


def _migrate_schema(conn: ConnectionAdapter) -> None:
    _drop_column_if_exists(conn, "rentals", "timeslot")
    _ensure_column(conn, "rentals", "user_id", "INTEGER")
    _ensure_column(conn, "users", "role", "TEXT NOT NULL DEFAULT 'user'")
    _ensure_column(conn, "cabinets", "last_idle_at", "TEXT")
    _ensure_column(conn, "cabinets", "active_card_count", "INTEGER NOT NULL DEFAULT 0")
    _ensure_column(conn, "cabinets", "host_ip", "TEXT")
    _ensure_column(conn, "cabinets", "ssh_port", "INTEGER NOT NULL DEFAULT 22")
    _ensure_column(conn, "rentals", "card_count", "INTEGER")
    _ensure_column(conn, "rentals", "stop_reason", "TEXT")
    _ensure_column(conn, "rental_allocations", "allocated_cards", "INTEGER NOT NULL DEFAULT 1")
    _ensure_column(conn, "rental_allocations", "device_indices", "TEXT")
    _ensure_column(conn, "rental_allocations", "instance_id", "TEXT")
    _ensure_column(conn, "rental_allocations", "container_name", "TEXT")
    _ensure_column(conn, "rental_allocations", "ssh_host", "TEXT")
    _ensure_column(conn, "rental_allocations", "ssh_port", "INTEGER")
    _ensure_column(conn, "rental_allocations", "ssh_username", "TEXT")
    _ensure_column(conn, "rental_allocations", "ssh_password", "TEXT")
    _ensure_column(conn, "rental_allocations", "ssh_command", "TEXT")
    _ensure_column(conn, "rental_allocations", "provisioning_status", "TEXT")
    _ensure_column(conn, "gpu_devices", "observed_status", "TEXT NOT NULL DEFAULT 'unknown'")
    _ensure_column(conn, "gpu_devices", "health", "TEXT")
    _ensure_column(conn, "gpu_devices", "usage_percent", "REAL")
    _ensure_column(conn, "gpu_devices", "memory_used_mb", "INTEGER")
    _ensure_column(conn, "gpu_devices", "memory_total_mb", "INTEGER")
    _ensure_column(conn, "gpu_devices", "process_count", "INTEGER NOT NULL DEFAULT 0")
    _ensure_column(conn, "gpu_devices", "last_seen_at", "TEXT")
    _backfill_cabinet_load_state(conn)
    _backfill_rental_card_count(conn)
    _backfill_cabinet_connection_fields(conn)
    _sync_gpu_devices_from_cabinets(conn)
    conn.execute(
        "UPDATE rental_allocations SET allocated_cards = 1 WHERE allocated_cards IS NULL OR allocated_cards < 1",
    )


def _backfill_cabinet_load_state(conn: ConnectionAdapter) -> None:
    rows = conn.execute(
        """
        SELECT id, status, capacity_cards, active_card_count
        FROM cabinets
        """
    ).fetchall()
    for row in rows:
        current_active = row["active_card_count"]
        if current_active not in (None, 0):
            normalized_status = cabinet_status_from_active_cards(int(current_active), int(row["capacity_cards"]))
            if normalized_status != row["status"]:
                conn.execute(
                    "UPDATE cabinets SET status = ? WHERE id = ?",
                    (normalized_status, row["id"]),
                )
            continue
        seeded_status = row["status"]
        capacity_cards = int(row["capacity_cards"])
        if seeded_status == "offline":
            active_card_count = 0
        elif seeded_status == "rented":
            active_card_count = capacity_cards
        elif capacity_cards == 1:
            active_card_count = 0
        else:
            active_card_count = max(1, capacity_cards // 2)
        normalized_status = cabinet_status_from_active_cards(active_card_count, capacity_cards)
        conn.execute(
            "UPDATE cabinets SET active_card_count = ?, status = ?, last_idle_at = NULL WHERE id = ?",
            (active_card_count, normalized_status, row["id"]),
        )


def _backfill_rental_card_count(conn: ConnectionAdapter) -> None:
    rows = conn.execute(
        """
        SELECT id, cabinet_type, cabinet_count, card_count
        FROM rentals
        """
    ).fetchall()
    for row in rows:
        if row["card_count"]:
            continue
        card_count = int(row["cabinet_count"])
        conn.execute(
            "UPDATE rentals SET card_count = ? WHERE id = ?",
            (card_count, row["id"]),
        )


def _backfill_cabinet_connection_fields(conn: ConnectionAdapter) -> None:
    rows = conn.execute(
        "SELECT id, cabinet_code, host_ip, ssh_port FROM cabinets"
    ).fetchall()
    for row in rows:
        host_ip = row.get("host_ip") if isinstance(row, dict) else row["host_ip"]
        ssh_port = row.get("ssh_port") if isinstance(row, dict) else row["ssh_port"]
        cabinet_code = row["cabinet_code"]
        inferred_ip = cabinet_code.rsplit("-", 1)[0] if "-" in cabinet_code else cabinet_code
        next_host_ip = host_ip or inferred_ip
        next_ssh_port = ssh_port or 22
        conn.execute(
            "UPDATE cabinets SET host_ip = ?, ssh_port = ? WHERE id = ?",
            (next_host_ip, next_ssh_port, row["id"]),
        )


def _sync_gpu_devices_from_cabinets(conn: ConnectionAdapter) -> None:
    cabinets = conn.execute(
        """
        SELECT id, cabinet_code, card_type, capacity_cards, active_card_count
        FROM cabinets
        """
    ).fetchall()
    for cabinet in cabinets:
        existing = conn.execute(
            "SELECT gpu_index, status, rental_id FROM gpu_devices WHERE cabinet_id = ?",
            (cabinet["id"],),
        ).fetchall()
        existing_by_index = {int(row["gpu_index"]): row for row in existing}
        capacity_cards = int(cabinet["capacity_cards"])
        active_card_count = int(cabinet["active_card_count"] or 0)
        allowed_indices = get_allowed_device_indices(cabinet["cabinet_code"], capacity_cards)
        for gpu_index in range(capacity_cards):
            if gpu_index in existing_by_index:
                row = existing_by_index[gpu_index]
                next_status = row["status"]
                if not row["rental_id"]:
                    if gpu_index not in allowed_indices:
                        next_status = "disabled"
                    elif row["status"] == "disabled":
                        next_status = "available"
                if next_status != row["status"]:
                    conn.execute(
                        "UPDATE gpu_devices SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE cabinet_id = ? AND gpu_index = ?",
                        (next_status, cabinet["id"], gpu_index),
                    )
                continue
            if gpu_index not in allowed_indices:
                status = "disabled"
            else:
                rented_allowed_before = sum(1 for idx in allowed_indices if idx < gpu_index)
                status = "rented" if rented_allowed_before < active_card_count else "available"
            conn.execute(
                """
                INSERT INTO gpu_devices (
                    cabinet_id, gpu_index, gpu_name, status, rental_id
                ) VALUES (?, ?, ?, ?, NULL)
                """,
                (cabinet["id"], gpu_index, cabinet["card_type"], status),
            )
        stale_indices = [idx for idx in existing_by_index if idx >= capacity_cards]
        if stale_indices:
            placeholders = ",".join("?" for _ in stale_indices)
            conn.execute(
                f"DELETE FROM gpu_devices WHERE cabinet_id = ? AND gpu_index IN ({placeholders}) AND rental_id IS NULL",
                [cabinet["id"], *stale_indices],
            )


def _ensure_column(conn: ConnectionAdapter, table_name: str, column_name: str, column_sql: str) -> None:
    columns = _get_columns(conn, table_name)

    if column_name in columns:
        return
    conn.execute(f"ALTER TABLE {table_name} ADD COLUMN {column_name} {column_sql}")


def _drop_column_if_exists(conn: ConnectionAdapter, table_name: str, column_name: str) -> None:
    columns = _get_columns(conn, table_name)
    if column_name not in columns:
        return
    if conn.backend == "sqlite":
        conn.execute(f"ALTER TABLE {table_name} DROP COLUMN {column_name}")
        return
    conn.execute(f"ALTER TABLE {table_name} DROP COLUMN IF EXISTS {column_name}")


def _get_columns(conn: ConnectionAdapter, table_name: str) -> set[str]:
    if conn.backend == "sqlite":
        return {
            row["name"]
            for row in conn.execute(f"PRAGMA table_info({table_name})").fetchall()
        }
    rows = conn.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = %s
        """,
        (table_name,),
    ).fetchall()
    return {row["column_name"] for row in rows}


def _seed_if_empty(conn: ConnectionAdapter) -> None:
    table_records = {
        "card_products": CARD_PRODUCTS,
        "user_price_configs": USER_PRICE_CONFIGS,
        "cabinets": build_cabinets(),
    }
    for table_name, records in table_records.items():
        if _table_count(conn, table_name):
            continue
        if table_name == "card_products":
            conn.executemany(
                """
                INSERT INTO card_products (
                    card_type, title, cabinet_desc, vram, cpu, memory, display_price
                ) VALUES (
                    :card_type, :title, :cabinet_desc, :vram, :cpu, :memory, :display_price
                )
                """,
                records,
            )
        elif table_name == "user_price_configs":
            conn.executemany(
                """
                INSERT INTO user_price_configs (
                    card_type, cabinet_type, hourly_user_price, enabled
                ) VALUES (
                    :card_type, :cabinet_type, :hourly_user_price, :enabled
                )
                """,
                records,
            )
        else:
            conn.executemany(
                """
                INSERT INTO cabinets (
                    cabinet_code, location, card_type, cabinet_type, capacity_cards,
                    day_hourly_power_cost, night_hourly_power_cost, status, last_idle_at, active_card_count,
                    host_ip, ssh_port
                ) VALUES (
                    :cabinet_code, :location, :card_type, :cabinet_type, :capacity_cards,
                    :day_hourly_power_cost, :night_hourly_power_cost, :status, NULL, :active_card_count,
                    :host_ip, :ssh_port
                )
                """,
                records,
            )

    _seed_users(conn)
    _seed_history_rentals(conn)


def _table_count(conn: ConnectionAdapter, table_name: str) -> int:
    return int(conn.execute(f"SELECT COUNT(*) AS count FROM {table_name}").fetchone()["count"])


def _sync_seed_reference_data(conn: ConnectionAdapter) -> None:
    conn.execute("DELETE FROM card_products")
    conn.execute("DELETE FROM user_price_configs")

    conn.executemany(
        """
        INSERT INTO card_products (
            card_type, title, cabinet_desc, vram, cpu, memory, display_price
        ) VALUES (
            :card_type, :title, :cabinet_desc, :vram, :cpu, :memory, :display_price
        )
        """,
        CARD_PRODUCTS,
    )

    conn.executemany(
        """
        INSERT INTO user_price_configs (
            card_type, cabinet_type, hourly_user_price, enabled
        ) VALUES (
            :card_type, :cabinet_type, :hourly_user_price, :enabled
        )
        """,
        USER_PRICE_CONFIGS,
    )

    seeded_by_code = {item["cabinet_code"]: item for item in build_cabinets()}
    existing_rows = conn.execute("SELECT id, cabinet_code FROM cabinets").fetchall()
    existing_codes = {row["cabinet_code"] for row in existing_rows}
    for row in existing_rows:
        cabinet = seeded_by_code.get(row["cabinet_code"])
        if not cabinet:
            continue
        conn.execute(
            """
            UPDATE cabinets
            SET
                location = ?,
                card_type = ?,
                cabinet_type = ?,
                capacity_cards = ?,
                day_hourly_power_cost = ?,
                night_hourly_power_cost = ?,
                host_ip = ?,
                ssh_port = ?
            WHERE id = ?
            """,
            (
                cabinet["location"],
                cabinet["card_type"],
                cabinet["cabinet_type"],
                cabinet["capacity_cards"],
                cabinet["day_hourly_power_cost"],
                cabinet["night_hourly_power_cost"],
                cabinet["host_ip"],
                cabinet["ssh_port"],
                row["id"],
            ),
        )

    missing = [cabinet for code, cabinet in seeded_by_code.items() if code not in existing_codes]
    if missing:
        conn.executemany(
            """
            INSERT INTO cabinets (
                cabinet_code, location, card_type, cabinet_type, capacity_cards,
                day_hourly_power_cost, night_hourly_power_cost, status, last_idle_at, active_card_count,
                host_ip, ssh_port
            ) VALUES (
                :cabinet_code, :location, :card_type, :cabinet_type, :capacity_cards,
                :day_hourly_power_cost, :night_hourly_power_cost, :status, NULL, :active_card_count,
                :host_ip, :ssh_port
            )
            """,
            missing,
        )


def _seed_users(conn: ConnectionAdapter) -> None:
    seeded_initial_users = False
    if not _table_count(conn, "users"):
        conn.executemany(
            """
            INSERT INTO users (
                username, password_hash, phone, nickname, avatar_url, balance, status, role
            ) VALUES (
                :username, :password_hash, :phone, :nickname, :avatar_url, :balance, :status, :role
            )
            """,
            DEFAULT_USERS,
        )
        seeded_initial_users = True
    else:
        _ensure_default_admin(conn)

    if not seeded_initial_users:
        return

    default_user = conn.execute(
        "SELECT id, balance FROM users WHERE username = ?",
        (DEFAULT_USERS[0]["username"],),
    ).fetchone()
    if not default_user:
        return

    conn.execute(
        """
        INSERT INTO user_balance_transactions (
            user_id, type, amount, balance_after, reference_type, reference_id, remark
        ) VALUES (?, 'recharge', ?, ?, 'seed', NULL, ?)
        """,
        (
            default_user["id"],
            float(default_user["balance"]),
            float(default_user["balance"]),
            "初始化充值",
        ),
    )


def _ensure_default_admin(conn: ConnectionAdapter) -> None:
    admin_user = next((user for user in DEFAULT_USERS if user.get("role") == "admin"), None)
    if not admin_user:
        return
    existing = conn.execute("SELECT id FROM users WHERE username = ?", (admin_user["username"],)).fetchone()
    if existing:
        conn.execute(
            "UPDATE users SET role = 'admin', status = 'active', updated_at = CURRENT_TIMESTAMP WHERE id = ?",
            (existing["id"],),
        )
        return
    conn.execute(
        """
        INSERT INTO users (
            username, password_hash, phone, nickname, avatar_url, balance, status, role
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            admin_user["username"],
            admin_user["password_hash"],
            admin_user["phone"],
            admin_user["nickname"],
            admin_user["avatar_url"],
            admin_user["balance"],
            admin_user["status"],
            admin_user["role"],
        ),
    )


def _seed_history_rentals(conn: ConnectionAdapter) -> None:
    default_user = conn.execute(
        "SELECT id FROM users WHERE username = ?",
        (DEFAULT_USERS[0]["username"],),
    ).fetchone()
    if not default_user:
        return

    existing = conn.execute(
        "SELECT COUNT(*) AS count FROM rentals WHERE user_id = ? AND status = 'cancelled'",
        (default_user["id"],),
    ).fetchone()["count"]
    if existing:
        return

    rows = [
        {
            **record,
            "user_id": default_user["id"],
        }
        for record in DEFAULT_HISTORY_RENTALS
    ]
    conn.executemany(
        """
        INSERT INTO rentals (
            user_id,
            card_type,
            cabinet_type,
            cabinet_count,
            card_count,
            started_at,
            ended_at,
            duration_seconds,
            hourly_user_price_total,
            hourly_power_cost_total,
            user_total_amount,
            power_cost_total,
            status,
            ip,
            password
        ) VALUES (
            :user_id,
            :card_type,
            :cabinet_type,
            :cabinet_count,
            :card_count,
            :started_at,
            :ended_at,
            :duration_seconds,
            :hourly_user_price_total,
            :hourly_power_cost_total,
            :user_total_amount,
            :power_cost_total,
            :status,
            :ip,
            :password
        )
        """,
        rows,
    )


def _adapt_query(sql: str, params: Any, backend: str) -> tuple[str, Any]:
    if backend == "sqlite":
        return sql, params
    query = sql.replace("?", "%s")
    if isinstance(params, dict):
        query = re.sub(r":([A-Za-z_][A-Za-z0-9_]*)", r"%(\1)s", query)
    return query, _adapt_params(params, backend)


def _adapt_params(params: Any, backend: str) -> Any:
    if backend == "sqlite" or params is None:
        return params
    if isinstance(params, list):
        return tuple(params)
    return params


def _with_returning_id(sql: str) -> str:
    stripped = sql.rstrip().rstrip(";")
    return f"{stripped} RETURNING id"
